# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  projectPath: 'src/NginxDash/NginxDash.csproj'

steps:
- script: dotnet build --configuration $(buildConfiguration) $(projectPath)
  displayName: 'dotnet build $(buildConfiguration)'
- script: |
    # dotnet tool install --global dotnet-reportgenerator-globaltool
    dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResults\Coverage\ /p:Exclude=[xunit*]* --logger "trx;LogFileName=TestResults.trx" --logger "xunit;LogFileName=TestResults.xml" 
    dotnet reportgenerator "-reports:TestResults\Coverage\coverage.cobertura.xml" "-targetdir:TestResults\Coverage" -reporttypes:HTML;HTMLSummary
  displayName: 'dotnet tests'
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
  displayName: 'publish tests'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '**/TestResults/coverage.cobertura.xml'
  displayName: 'publish coverage'
