version: '3.4'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ~/docker_volumes/wayproyect.com/nginx/conf:/etc/nginx/conf.d
      - ~/docker_volumes/wayproyect.com/certbot/conf:/etc/letsencrypt
      - ~/docker_volumes/wayproyect.com/certbot/www:/var/www/certbot
    restart: always
    ports:
      - '1080:80'
      - '1443:443'
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ~/docker_volumes/wayproyect.com/certbot/conf:/etc/letsencrypt
  #     - ~/docker_volumes/wayproyect.com/certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginxdash:
    image: docker-registry.wayproyect.com/nginxdash
    container_name: wayproyect_nginxdash
    build:
      context: ./src
      dockerfile: NginxDash/Dockerfile
    restart: on-failure
    volumes:
      - ~/docker_volumes/wayproyect.com/nginx/conf:/etc/nginx/conf.d
      - //var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5001:80"